sudo: required
services:
    - docker

before_install:
    - docker build -t gentlyawesome/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true gentlyawesome/react-test npm test

after_success:
    - docker build -t gentlyawesome/multi-client ./client
    - docker build -t gentlyawesome/multi-nginx ./nginx
    - docker build -t gentlyawesome/multi-server ./server
    - docker build -t gentlyawesome/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push gentlyawesome/multi-client
    - docker push gentlyawesome/multi-nginx
    - docker push gentlyawesome/multi-server
    - docker push gentlyawesome/multi-worker

deploy: 
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: docker-multi-container
    env: DockerMultiContainer-env
    bucket_name: docker-multi-container 
    bucket_path: docker-multi-container
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on: 
        branch: master